![task](https://github.com/Werest/DevOps/blob/4bcb891fabc45f7aa9e58b4b7c0ad8bb89440ee9/HW4/task1/task0.png)

# Задача 1
запустить mysql для приложения
docker run -dit -p 3306:3306 -e MYSQL_ROOT_PASSWORD="YtReWq4321" -e MYSQL_DATABASE="virtd" -e MYSQL_USER="app" -e MYSQL_PASSWORD="QwErTy1234" --name db mysql

```
cd ~
python3 -m venv myenv
source myenv/bin/activate
cd /media/sf_Devops/DevOps/HW4/shvirtd-example-python
pip install -r requirements.txt
```
db_table = requests

### Выполнение
![\Werest\DevOps\HW4\task1\task0.png](https://github.com/Werest/DevOps/blob/4bcb891fabc45f7aa9e58b4b7c0ad8bb89440ee9/HW4/task1/task0.png)
#### Пункт 3
![\Werest\DevOps\HW4\task1\Задача 1.png](https://github.com/Werest/DevOps/blob/4bcb891fabc45f7aa9e58b4b7c0ad8bb89440ee9/HW4/task1/%D0%97%D0%B0%D0%B4%D0%B0%D1%87%D0%B0%201.png)
#### Пункт 4
[\Werest\DevOps\HW4\task1\Задача 1 - 3.png](https://github.com/Werest/DevOps/blob/4bcb891fabc45f7aa9e58b4b7c0ad8bb89440ee9/HW4/task1/%D0%97%D0%B0%D0%B4%D0%B0%D1%87%D0%B0%201%20-%203.png)

# Задача 3
Возникала ошибка внутри контейнера haproxy, помогло лишь user: "root", тогда без проблем запустилась данная конфигурация
![\Werest\DevOps\HW4\task1\Задание 3.png](https://github.com/Werest/DevOps/blob/4bcb891fabc45f7aa9e58b4b7c0ad8bb89440ee9/HW4/task1/%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5%203.png)

Выполненые задания
![\Werest\DevOps\HW4\task1\Задание 3 - 1.png](https://github.com/Werest/DevOps/blob/4bcb891fabc45f7aa9e58b4b7c0ad8bb89440ee9/HW4/task1/%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5%203%20-%201.png)

![\Werest\DevOps\HW4\task1\Задание 3 - 1.png](https://github.com/Werest/DevOps/blob/4bcb891fabc45f7aa9e58b4b7c0ad8bb89440ee9/HW4/task1/%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5%203%20-%201.png)

# Задача 4

# Задача 6

# Задача 6.1